# Generated by Django 3.2 on 2021-04-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handicapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('cin', models.CharField(blank=True, max_length=20)),
                ('birthday', models.DateField(blank=True)),
                ('birth_address', models.CharField(blank=True, max_length=100)),
                ('guardian', models.CharField(blank=True, max_length=50)),
                ('handicap_Type', models.CharField(blank=True, max_length=50)),
                ('has_card', models.BooleanField(default=False)),
                ('request_card', models.BooleanField(default=False)),
            ],
        ),
    ]
