# Generated by Django 3.2 on 2021-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicapped', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handicapped',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='handicapped',
            name='birth_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='handicapped',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handicapped',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='handicapped',
            name='guardian',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='handicapped',
            name='handicap_Type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='handicapped',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
