# Generated by Django 3.2 on 2021-04-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicapped', '0002_auto_20210409_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='handicapped',
            name='Genre',
            field=models.CharField(default='r', max_length=50),
            preserve_default=False,
        ),
    ]
