# Generated by Django 3.2 on 2021-04-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicapped', '0003_handicapped_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='handicapped',
            name='delete_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handicapped',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
