# Generated by Django 3.2 on 2021-04-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handicapped', '0005_rename_genre_handicapped_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handicapped',
            name='has_card',
        ),
        migrations.RemoveField(
            model_name='handicapped',
            name='request_card',
        ),
    ]
