# Generated by Django 3.2 on 2021-04-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicapped', '0007_auto_20210410_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='handicapped',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
