# Generated by Django 3.2 on 2021-04-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0019_projectvisit'),
        ('handicapped', '0008_handicapped_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='handicapped',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_box.association'),
        ),
    ]
