# Generated by Django 3.2 on 2021-04-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handicapped', '0007_auto_20210410_1418'),
        ('social_box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('submiting_date', models.DateField(auto_now_add=True)),
                ('approving_date', models.DateField()),
                ('handicapped', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='handicapped.handicapped')),
            ],
        ),
        migrations.DeleteModel(
            name='SocialBox',
        ),
    ]
