# Generated by Django 3.2 on 2021-04-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0003_alter_project_approving_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
