# Generated by Django 3.2 on 2021-04-15 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0007_association'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationHr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('month_salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('year_salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_box.association')),
            ],
        ),
    ]
