# Generated by Django 3.2 on 2021-04-15 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0008_associationhr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('students_number', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=9)),
                ('programm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('guardian', models.CharField(blank=True, max_length=50, null=True)),
                ('handicap_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('programm_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('services', models.CharField(blank=True, max_length=50, null=True)),
                ('Association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_box.association')),
            ],
        ),
    ]
