# Generated by Django 3.2 on 2021-04-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0009_associationhistory_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='AssociationStudent',
        ),
        migrations.AddField(
            model_name='associationhr',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='associationhr',
            name='month_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='associationhr',
            name='year_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
