# Generated by Django 3.2 on 2021-04-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0010_auto_20210416_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
