# Generated by Django 3.2 on 2021-04-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0012_auto_20210416_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associationstudent',
            old_name='Association',
            new_name='association',
        ),
        migrations.AlterField(
            model_name='associationstudent',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
