# Generated by Django 3.2 on 2021-04-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0014_alter_associationstudent_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationstudent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
