# Generated by Django 3.2 on 2021-04-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0015_associationstudent_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationstudent',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
