# Generated by Django 3.2 on 2021-04-17 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0016_associationstudent_deleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationhistory',
            name='association',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='social_box.association'),
            preserve_default=False,
        ),
    ]
