# Generated by Django 3.2 on 2021-04-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0017_associationhistory_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationhistory',
            name='programm',
        ),
        migrations.AddField(
            model_name='associationhistory',
            name='A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='associationhistory',
            name='B',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='associationhistory',
            name='C',
            field=models.BooleanField(default=False),
        ),
    ]
