# Generated by Django 3.2 on 2021-04-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0018_auto_20210417_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('visitors', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_box.project')),
            ],
        ),
    ]
