# Generated by Django 3.2 on 2021-04-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_box', '0019_projectvisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssociationStudent',
        ),
    ]
