# Generated by Django 3.2 on 2021-04-10 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handicapped', '0007_auto_20210410_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submiting_date', models.DateTimeField(auto_now_add=True)),
                ('finishing_date', models.DateTimeField(auto_now=True)),
                ('is_finish', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('handicapped', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='handicapped.handicapped')),
            ],
        ),
    ]
