# Generated by Django 3.2 on 2021-04-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card',
            field=models.FileField(blank=True, null=True, upload_to='cards/'),
        ),
    ]
