# Generated by Django 3.2 on 2021-04-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='deleted_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
