# Generated by Django 3.2 on 2021-04-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_deleted_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='deleted_description',
            new_name='delete_description',
        ),
    ]
