# Generated by Django 3.2 on 2021-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_deleted_description_food_delete_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='finishing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
